### ISSUE TITLE
[Enhancement] Add a component to each object that is currently part of EQS

### ISSUE THREAD

**Issue by owlboy** [JordoVR/EasyQuestSwitch#1]
I finally had a chance to try out using this script today, and it seems pretty fantastic. 

As I start to build up a list of configured things, I quickly realized I have no quick way to tell if an object is entered in EQS without comparing the object to the big list in the EQS window by hand/eye.

It would be fantastic if each object entered in EQS placed a component on the object that merely indicated it was entered and gives you a button to jump to that entry in EQS.

Even cooler would be to show the EQS interface for all added components right in the inspector on the object, but I can understand if that is quite a big ask/just not how this is designed. But having a signal that "this object has one or more components in EQS" and a button to jump to those entries in EQS would be great!

**Comment by JordoVR** [comment]
Hey, thanks for using EQS & providing feedback!

It seems like an interesting challenge, not sure if it's going to be possible but I'll definitely check this out, can't really give an ETA sadly, as I was about to start working on my UDON map for the next month or so.
I'll update you on here if I manage to get it working.

From what I understand it would be on hierarchy and on component? Don't want it to be too intrusive so I'll probably have it be a settings checkmark.

**Comment by owlboy** [comment]
Oh, having it on the hierarchy would be interesting, but that would only be a high-level indicator that a component on that object is in EQS. I agree it would be good to have an option to turn that on and off.

But it would not show what Components are being affected by EQS or allow you to jump to them in EQS. 

Because EQS currently uses a Component model instead of a GameObject model (You add Components to EQS, not the whole GameObject. And Components are not grouped by GameObject in the EQS window) I think the Inspector needs a Component that lists the Components on that GameObject that are entered in EQS. And needs to include a button to quickly jump to the Component in EQS.

And again, this is all in service of a world with hundreds of GameObjects, each with multiple components being modified by EQS. The current UI is fine for 10-30 GameObjects or so. But I think it falls apart for large projects.

For instance, I think something like this would be a mandatory tool for someone to creatively and successfully create an alternative build of something like The Great Pug for Quest. Without something like EQS, maintenance and sync between two scenes would be a nightmare due to just how many objects need to be managed in such a project.
<img width="241" alt="image" src="https://user-images.githubusercontent.com/237349/87459986-c14b5d80-c5d1-11ea-8a66-d1d2030c7707.png">

**Comment by JordoVR** [comment]
I have thought of the problem and I've had three ideas, unfortunately two of them seem to fall flat.

- First off is yours of adding a component on the gameobject itself, while I wasn't too keen on the idea at first it seems like it's slowly turning out to be the most reliable solution, I personally dislike it because I made EQS to be as invisible as possible, everything is contained in one GameObject in the scene that the end user cannot actually see, or click and that isn't compiled with the map.
Adding another component would mean possible issues with prefabs for example, which I'd like to avoid but now that I'm typing this, maybe I have a little idea for that one issue.
One other issue is the order of the component, for consistency and readability purpose I would like it to be at the very top at least and I'm not sure that's possible with Unity (haven't looked into it yet).

- Second one is creating a custom inspector for the GameObject component, that way I can display it directly below the GameObject header right at the top, the issue is that I have to create the custom inspector and I don't like that, it would create a conflict with any other addon doing the same thing...

- Third one which was my favorite but so far has turned out to be impossible was to possibly hijack the InspectorWindow with reflection and display additional information for the components, including a "View in EQS" button but yeah so far I've had no luck on that.

I'll think about it some more and try to implement something.

**Comment by JordoVR** [comment]
@owlboy A functionality like this was added in the newest EasyQuestSwitch 1.2.0, it appears like this:
![image](https://user-images.githubusercontent.com/9134625/186000722-bc4e0bd8-7fc4-4b48-b92a-19ae25eabbdc.png)
