### ISSUE TITLE
Easy Quest Switch 1.3.0 design mistake

### ISSUE THREAD

**Issue by MrDummyNL** [JordoVR/EasyQuestSwitch#24]
Oh boy...

I upgrade to 1.3.0 from 1.2.1
All looks good....
I swap to Andoird side.

Everything looks so weird dark. Did i made mistake? 
Then i noticed later all materials have black color.

WHAT? What is going on here?
Then i found out 1.3.0 added extra options to materials to SET THE COLOR. And GUESS WHAT?
Because 1.2.1 has no colors, so 1.3.0 decide it with BLACK COLOR.

THAT IS STUPID MISTAKE.

Sure, more features is nice. But because of this problem, now every material in EQS get by standard BLACK color, i am so surprised why developer made big mistake here. NEVER decide color by YOURSELF (program itself) because there is no color set, causing all materials will get WRONG color. And world creators will not happy with it, because they are forced to re-set every material again AND ALSO SET EQS AGAIN. That is double work. 

Seriously, this is super bad design. Many creators will shocked with it, if there are 1000 materials in EQS, i am sure nobody is happy with black color by default.

So.... what is better solution?
- ignore color, don't add it if it's still null. Just like 1.2.1.
- or scan for materials and apply missing colors. THIS IS RECOMMENDED.

EQS has no material scanning function, and that is exactly the problem why everything will go bad with 1.3.0.
I am downgrading to 1.2.1 because i am not gonna set everything again. DO YOU WORK correct, scan to all materials and apply colors from all materials inside EQS, that is how you make it correct and avoid color problems.
Apply by default black color? Who made this decision? You as developer should know this will bring only more problems and extra work for creators.

Seriously. I program stuff too, and i am just shocked how dumb the 1.3.0 update is. I know this can avoided, but ... you didn't think about the problems with 1.3.0.

No problem if you started fresh, but right now with existing world, it's HUGE problem. I discovered later and now i need backup to fix all wrong materials. Really, this is not funny. It's clearly design mistake.

**Comment by JordoVR** [comment]
Hey, I find this issue written in an extremely rude language, I understand your frustration and I apologize for it happening but I think you could've worded this better.

This was an honest bug that didn't get caught by QA because I lacked the QA step for this, to give a rundown, a week ago I got informed that EQS had been unusable in 2022 projects for close to two months and I hastily prepared a fix, in the process I saw an opportunity to integrate PRs into this release because I didn't think I would prepare a new release any time soon (1.2.0 was released in August 2022).

I prepared and got the test cases for the update successfully completed but I missed a case where users would have an existing material in EQS and the current values on the new fields wouldn't have been captured from the scene and instead be set as the default.
Even then, the reasonable assumption would be that Unity would just have a default Color be white... Well apparently not, it interpret that lack of data as completely black, so no I did not "decide to make the default color black".

Shortly after release, I got the first report of the issue and immediately updated the Known Issues with this information, knowing I wouldn't have time to fix it that week and it would take me longer to come up with a 1.3.1 release fixing this.
I will work on a fix next week

**Comment by JordoVR** [comment]
I'll also pull the download for 1.3.0 for now.

**Comment by JordoVR** [comment]
This was resolved in v1.3.1 just released on the VCC curated listings.
https://github.com/vrchat-community/EasyQuestSwitch/releases/tag/v1.3.1
